services:
  - docker

before_script:
  - composer install --ignore-platform-reqs

script:
  - docker run --rm -v "$PWD:/code" humanmade/plugin-tester --testsuite=Unit --no-coverage
  
  
cache:
  timeout: 1000
  directories:
    - vendor
